title: Pratik Gupte
url: http://randomsurfer.in
description: 'Personal site of Pratik Gupte'
markdown: kramdown
keywords:
 - Pratik Gupte
 - Pratik Vinay Gupte
 - randomsurfer

author:
    name: Pratik Gupte
    email: pratik.gupte@gmail.com
    github: http://github.com/randomsurfer
    linkedin: https://www.linkedin.com/in/pgupte/
    
sections:
 - research
 - projects
 - photography

stylesheets:
 - /assets/themes/default/css/screen.css?52480=52480
 - /assets/themes/default/css/print.css
scripts:
 - http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js    
 - /assets/themes/default/js/site.min.js?131513?131513
colors:
    highlights:
        blue: '#009ff7'
        green: '#87d14b'
        red: '#FF007C'
    mono:
        dark: '#000000'
        medium: '#777777'
        light: '#FFFFFF'
    bg: '#EAF1F4'
    
pygments: false
permalink: pretty 
exclude:
 - Rakefile
 - README.markdown
 - .git
